backend:
  name: git-gateway
  branch: main

media_folder: "img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "content"
    label: "Content"
    files:
      # 保持现有的所有页面...
      - name: "homepage"
        label: "Homepage"
        file: "homepage-data.json"
        fields:
          - {label: "Page Title", name: "page_title", widget: "string", default: "Initial Research", required: true, hint: "Title that appears in browser tab"}
          - {label: "Hero Image", name: "hero_image", widget: "image", required: true, hint: "Main background image for homepage"}
          - {label: "Hero Image Alt Text", name: "hero_alt_text", widget: "string", default: "Initial Research", required: true, hint: "Alternative text for screen readers"}

      - name: "fellowship"
        label: "Fellowship Page"
        file: "fellowship-data.json"
        fields:
          - {label: "Page Title", name: "title", widget: "string", default: "Fellowship - Inaugural Cohort", required: true}
          - {label: "Main Heading", name: "heading", widget: "string", default: "Fellowship", required: true}
          - {label: "Introduction", name: "intro", widget: "markdown", required: true, hint: "Fellowship program description. Use double line breaks for paragraphs."}
          
          - label: "Cohorts"
            name: "cohorts"
            widget: "list"
            required: false
            hint: "Add different fellowship cohorts (e.g., 2025/2026, 2027, etc.)"
            summary: "{{fields.cohort_title}}"
            fields:
              - {label: "Cohort Title", name: "cohort_title", widget: "string", required: true, hint: "e.g., 2025/2026 Inaugural Cohort, 2027 Cohort"}
              - {label: "Display Order", name: "order", widget: "number", default: 1, hint: "Lower numbers appear first"}
              - {label: "Show Cohort", name: "show_cohort", widget: "boolean", default: true, hint: "Toggle to show or hide this cohort"}
              
              - label: "Fellows"
                name: "fellows"
                widget: "list"
                required: false
                hint: "Add fellows for this cohort"
                summary: "{{fields.number}}. {{fields.name}}"
                fields:
                  - {label: "Fellow Number", name: "number", widget: "string", required: true, hint: "e.g., 01, 02, 03"}
                  - {label: "Fellow Name", name: "name", widget: "string", required: true}
                  - {label: "Fellow ID", name: "id", widget: "string", required: true, hint: "Unique ID (e.g., te-editions-2025, john-smith-2027)"}
                  - {label: "Fellow Title/Position", name: "fellow_title", widget: "string", required: false, hint: "Optional title or position"}
                  - {label: "Fellow Bio", name: "bio", widget: "markdown", required: true, hint: "Full biography. Use **text** for bold and double line breaks for paragraphs"}
                  
                  - label: "Image Type"
                    name: "image_type"
                    widget: "select"
                    options:
                      - {label: "Single Image", value: "single"}
                      - {label: "Carousel", value: "carousel"}
                    default: "single"
                    required: true
                  
                  - {label: "Main Image", name: "image", widget: "image", required: true, hint: "Main image or first carousel image"}
                  - {label: "Image Caption", name: "caption", widget: "string", required: false}
                  
                  - label: "Additional Carousel Images"
                    name: "additional_images"
                    widget: "list"
                    required: false
                    hint: "Only for carousel image type - add additional images here"
                    fields:
                      - {label: "Image", name: "src", widget: "image", required: true}
                      - {label: "Caption", name: "caption", widget: "string", required: false}

      - name: "calendar"
        label: "Calendar Page"
        file: "calendar-data.json"  
        fields:
          - {label: "Page Title", name: "title", widget: "string", required: false}
          - label: "Events"
            name: "events"
            widget: "list"
            required: false
            fields:
              - {label: "Event ID", name: "id", widget: "number", required: true}
              - {label: "Event Title", name: "title", widget: "string", required: true}
              - {label: "Subtitle/Type", name: "subtitle", widget: "string", required: true, hint: "e.g., exhibition, screening, lecture"}
              - {label: "Event Date", name: "date", widget: "datetime", required: true, format: "YYYY-MM-DDTHH:mm:ssZ", date_format: "YYYY-MM-DD", time_format: "HH:mm"}
              - {label: "Display Date (MM.DD.YY)", name: "displayDate", widget: "string", required: true, hint: "Format as MM.DD.YY (e.g., 05.20.25)"}
              - {label: "Time Display", name: "timeDisplay", widget: "string", required: true, hint: "e.g., 6pm to 9pm"}
              - {label: "Event Image", name: "image", widget: "image", required: false}
              - {label: "Description", name: "description", widget: "text", required: true}
              - {label: "RSVP Link", name: "rsvpLink", widget: "string", required: false}
              - {label: "External Link (for past events)", name: "link", widget: "string", required: false}

      # 其他现有页面保持不变...
      - name: "communityhours"
        label: "Community Hours Page"
        file: "communityhours-data.json"
        fields:
          - {label: "Page Title", name: "title", widget: "string", default: "Community Hours", required: true}
          - {label: "Hours", name: "hours", widget: "string", default: "11:00 am– 4:00 pm", required: true}
          - {label: "Description", name: "description", widget: "markdown", required: true, hint: "Main description of community hours. Use double line breaks for paragraphs."}

      - name: "seasonaldinner"
        label: "Seasonal Dinner Page"
        file: "seasonaldinner-data.json"
        fields:
          - {label: "Page Title", name: "title", widget: "string", default: "The Seasonal (shijie/时节) Dinner at Initial Research", required: true}
          - {label: "Main Description", name: "description", widget: "markdown", required: true, hint: "Main description of the seasonal dinner. Use double line breaks for paragraphs."}

      # FIXED: Mission & About Page with Additional Sections at ROOT level
      - name: "mission"
        label: "Mission & About Page"
        file: "mission-data.json"
        fields:
          - label: "Mission Section"
            name: "mission"
            widget: "object"
            required: false
            collapsed: true
            fields:
              - {label: "Section Title", name: "title", widget: "string", default: "Mission", required: false}
              - {label: "Mission Content", name: "content", widget: "markdown", required: false, hint: "Mission statement content. Use double line breaks for paragraphs. Leave empty to hide this section."}
              - {label: "Display Order", name: "order", widget: "number", default: 1, hint: "Lower numbers appear first on the page"}
              - {label: "Show Section", name: "visible", widget: "boolean", default: false, hint: "Toggle to show or hide this section"}
          
          - label: "Vision Section"
            name: "vision"
            widget: "object"
            required: false
            collapsed: true
            fields:
              - {label: "Section Title", name: "title", widget: "string", default: "Vision", required: false}
              - label: "Vision Statements"
                name: "items"
                widget: "list"
                required: false
                hint: "Add your vision statements. Leave empty to hide this section."
                field: {label: "Vision Statement", name: "statement", widget: "string"}
              - {label: "Display Order", name: "order", widget: "number", default: 2, hint: "Lower numbers appear first on the page"}
              - {label: "Show Section", name: "visible", widget: "boolean", default: false, hint: "Toggle to show or hide this section"}
          
          - label: "Team Section"
            name: "people"
            widget: "object"
            required: false
            collapsed: true
            fields:
              - {label: "Section Title", name: "title", widget: "string", default: "Team", required: false}
              - label: "Team Members"
                name: "team"
                widget: "list"
                required: false
                hint: "Click 'Add Team Members' to add new team members. Leave empty to hide this section."
                summary: "{{fields.name}} - {{fields.role}}"
                fields:
                  - {label: "Name", name: "name", widget: "string", required: true}
                  - {label: "Role/Title", name: "role", widget: "string", required: true}
                  - {label: "Display Order", name: "member_order", widget: "number", default: 1, hint: "Order within the team section"}
              - {label: "Display Order", name: "order", widget: "number", default: 3, hint: "Lower numbers appear first on the page"}
              - {label: "Show Section", name: "visible", widget: "boolean", default: false, hint: "Toggle to show or hide this section"}
          
          - label: "Contact Section"  
            name: "contact"
            widget: "object"
            required: false
            collapsed: true
            fields:
              - {label: "Section Title", name: "title", widget: "string", default: "Contact", required: false}
              - {label: "Organization Name", name: "organization", widget: "string", default: "Initial Research", required: false}
              - {label: "Email Address", name: "email", widget: "string", required: false}
              - {label: "Phone", name: "phone", widget: "string", required: false}
              - {label: "Address", name: "address", widget: "string", required: false}
              - {label: "Additional Info", name: "additional", widget: "text", required: false}
              - {label: "Display Order", name: "order", widget: "number", default: 4, hint: "Lower numbers appear first on the page"}
              - {label: "Show Section", name: "visible", widget: "boolean", default: false, hint: "Toggle to show or hide this section"}

          - label: "Additional Sections"
            name: "additional_sections"
            widget: "list"
            required: false
            collapsed: false
            hint: "Add any additional custom sections here"
            summary: "{{fields.title}}"
            fields:
              - {label: "Section Title", name: "title", widget: "string", required: false, hint: "Custom section title"}
              - {label: "Section Content", name: "content", widget: "markdown", required: false, hint: "Custom section content. Use **text** for bold and double line breaks for paragraphs. Leave empty to hide this section."}
              - {label: "Display Order", name: "order", widget: "number", default: 5, hint: "Lower numbers appear first on the page"}
              - {label: "Show Section", name: "visible", widget: "boolean", default: true, hint: "Toggle to show or hide this section"}

      - name: "supportus"
        label: "Support Us Page"
        file: "supportus-data.json"
        fields:
          - {label: "Page Title", name: "page_title", widget: "string", default: "Support Us", required: true}
          - label: "Support Section"
            name: "support_section"
            widget: "object"
            fields:
              - {label: "Section Title", name: "title", widget: "string", default: "Support Us", required: true}
              - {label: "Introduction Text", name: "intro", widget: "markdown", required: true, hint: "Main support content including patron levels intro"}
          - label: "Patron Levels"
            name: "patron_levels"
            widget: "object"
            fields:
              - {label: "Section Title", name: "title", widget: "string", default: "", required: false, hint: "Leave empty if no separate title needed"}
              - label: "Levels"
                name: "levels"
                widget: "list"
                required: false
                hint: "Add different patron support levels"
                fields:
                  - {label: "Level Name", name: "name", widget: "string", required: true, hint: "e.g., Friend, Supporter, Founding Patron"}
                  - {label: "Annual Amount", name: "amount", widget: "string", required: true, hint: "e.g., US$3,000, US$8,000"}
          - label: "Additional Content"
            name: "additional_content"
            widget: "object"
            fields:
              - {label: "Content", name: "text", widget: "markdown", required: true, hint: "Thank you message, donation instructions, and tax info"}
          - label: "Donor Recognition"
            name: "donor_recognition"
            widget: "object"
            fields:
              - {label: "Section Title", name: "title", widget: "string", default: "Donor Board", required: true}
              - label: "Donor Categories"
                name: "categories"
                widget: "list"
                required: false
                hint: "Add different donor recognition levels"
                fields:
                  - {label: "Category Name", name: "name", widget: "string", required: true, hint: "e.g., Friends, Supporters, Founding Patrons"}
                  - {label: "Donor Names", name: "donors", widget: "text", required: false, hint: "List donor names, separated by commas"}

      # NEW: Exhibitions Manager - Client can manage all exhibitions
      - name: "exhibitions_manager"
        label: "Exhibitions Manager"
        file: "exhibitions-manager.json"
        fields:
          - {label: "Exhibitions Page Title", name: "page_title", widget: "string", default: "Exhibitions", required: true}
          - label: "All Exhibitions"
            name: "exhibitions"
            widget: "list"
            required: false
            hint: "Click 'Add All Exhibitions' to create new exhibition pages"
            summary: "{{fields.title}} ({{fields.date_range}})"
            fields:
              - {label: "Exhibition Title", name: "title", widget: "string", required: true}
              - {label: "Exhibition Date Range", name: "date_range", widget: "string", required: true, hint: "e.g., April 15 - June 30, 2025"}
              - {label: "URL Slug", name: "slug", widget: "string", required: true, hint: "URL friendly name (e.g., embodied-memories-2025). Only use letters, numbers and hyphens"}
              - {label: "Show in Exhibition List", name: "show_in_list", widget: "boolean", default: true, hint: "Uncheck to hide this exhibition from public view"}
              - {label: "Display Order", name: "order", widget: "number", default: 1, hint: "Lower numbers appear first. The first exhibition becomes the main exhibition page"}
              - label: "Exhibition Images"
                name: "images"
                widget: "list"
                summary: "{{fields.caption}}"
                required: false
                hint: "Add all images for this exhibition"
                fields:
                  - {label: "Image", name: "url", widget: "image", required: true}
                  - {label: "Alt Text", name: "alt", widget: "string", required: false, hint: "Image description for screen readers"}
                  - {label: "Image Caption", name: "caption", widget: "string", required: false, hint: "Caption displayed below the image"}
              - {label: "Exhibition Description", name: "description", widget: "markdown", required: true, hint: "Full exhibition description. Use **text** for bold and double line breaks for paragraphs"}
              - {label: "PDF File", name: "pdf_file", widget: "file", required: false, hint: "Upload exhibition related PDF file"}
              - {label: "PDF Button Text", name: "pdf_button_text", widget: "string", default: "download exhibition pdf", required: false}
          
  - name: "navigation"
    label: "Navigation"
    files:
      - name: "main_nav"
        label: "Main Navigation"
        file: "navigation-data.json"
        fields:
          - label: "Site Title"
            name: "site_title"
            widget: "string"
            required: true
          - label: "Navigation Items"
            name: "nav_items"
            widget: "list"
            fields:
              - {label: "Menu Label", name: "label", widget: "string", required: true}
              - {label: "Direct Link (optional)", name: "direct_link", widget: "string", required: false, hint: "Leave empty if this is a dropdown"}
              - {label: "Visible", name: "visible", widget: "boolean", default: true}
              - label: "Dropdown Items"
                name: "dropdown_items"
                widget: "list"
                required: false
                fields:
                  - {label: "Item Label", name: "label", widget: "string", required: true}
                  - {label: "Link URL", name: "link", widget: "string", required: true}
                  - {label: "Visible", name: "visible", widget: "boolean", default: true}
      
      # NEW: Footer Settings
      - name: "footer"
        label: "Footer"
        file: "footer-data.json"
        fields:
          - {label: "Footer Text", name: "footer_text", widget: "string", default: "124 Gallery Street, New York, NY 10001", required: true, hint: "Text that appears in the footer across all pages"}
          - {label: "Show Footer", name: "show_footer", widget: "boolean", default: true, hint: "Toggle to show or hide the footer"}
      
      # NEW: Homepage Settings
      - name: "homepage_settings"
        label: "Homepage Settings"
        file: "homepage-settings.json"
        fields:
          - label: "Default Homepage"
            name: "default_homepage"
            widget: "select"
            required: true
            default: "custom"
            hint: "Choose which page visitors see when they go to your main website"
            options:
              - {label: "Calendar (Events)", value: "calendar"}
              - {label: "Current Exhibition", value: "exhibition"}
              - {label: "Community Hours", value: "community-hours"}
              - {label: "Fellowship", value: "fellowship"}
              - {label: "Custom Landing Page", value: "custom"}
          - label: "Custom Homepage Content"
            name: "custom_content"
            widget: "object"
            hint: "Only used if 'Custom Landing Page' is selected above"
            fields:
              - {label: "Page Title", name: "title", widget: "string", required: false, default: "Welcome to Initial Research"}
              - {label: "Hero Image", name: "hero_image", widget: "image", required: false}
              - {label: "Main Content", name: "content", widget: "markdown", required: false, hint: "Main content for custom homepage"}
              - label: "Featured Links"
                name: "featured_links"
                widget: "list"
                required: false
                hint: "Add buttons/links to highlight on homepage"
                fields:
                  - {label: "Link Text", name: "text", widget: "string", required: true}
                  - {label: "Link URL", name: "url", widget: "string", required: true}
                  - {label: "Button Style", name: "style", widget: "select", options: ["primary", "secondary"], default: "primary"}
